spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_jude
      username: root
      password: 123321
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false